### ISSUE TITLE
Could not load config file.

### ISSUE THREAD

**Issue by Destiny1231** [roramirez/MMM-ImagesPhotos#24]
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-ImagesPhotos/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/serveronly/index.js

sry for bad englich but i have this problem and can´t fix it.

Require stack:
- /home/pi/MagicMirror/modules/MMM-ImagesPhotos/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/serveronly/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-ImagesPhotos/node_helper.js:10:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-ImagesPhotos/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/serveronly/index.js'
  ]

**Comment by mickecamino** [comment]
Login to MagicMirror:
`
cd MagicMirror/modules/MMM-ImagesPhotos
`
Run
`
npm install request
`
